use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand, ValueEnum};
use mesh_proto::{
    HealthCheckConfig, HealthCheckMode, IpcRequest, IpcResponse, MeshConfig, NodeRole, Protocol,
};
use tracing_subscriber::EnvFilter;

#[derive(Parser)]
#[command(
    name = "mesh-proxy",
    about = "Decentralized P2P port forwarding and service discovery",
    version
)]
struct Cli {
    /// Path to config file.
    #[arg(long, global = true, default_value_os_t = MeshConfig::default_config_path())]
    config: PathBuf,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Start the mesh-proxy daemon.
    Start {
        /// Node role: control or edge.
        #[arg(long)]
        role: Role,
    },

    /// Stop the running daemon.
    Stop,

    /// Show daemon status.
    Status {
        /// Output format.
        #[arg(long, default_value_t = OutputFormat::Text)]
        output: OutputFormat,
    },

    /// Expose a local service to the mesh network.
    Expose {
        /// Service name (unique identifier on this node).
        #[arg(long)]
        name: String,

        /// Local address the service listens on (e.g. "127.0.0.1:8080" or "/tmp/foo.sock").
        #[arg(long)]
        addr: String,

        /// Transport protocol.
        #[arg(long, default_value_t = TransportProtocol::Tcp)]
        protocol: TransportProtocol,

        /// Health check mode (tcp_connect, unix_connect, http_get).
        #[arg(long)]
        health_check_mode: Option<HealthCheckModeArg>,

        /// Health check target (overrides addr for probe, e.g. an HTTP URL).
        #[arg(long)]
        health_check_target: Option<String>,
    },

    /// Accept an edge node's join ticket (control node only).
    Accept {
        /// The join ticket generated by the edge node.
        ticket: String,

        /// Optional friendly name for the edge node.
        #[arg(long)]
        name: Option<String>,
    },
}

/// Node role selection, maps to `NodeRole` from mesh-proto.
#[derive(Debug, Clone, Copy, ValueEnum)]
enum Role {
    Control,
    Edge,
}

impl From<Role> for NodeRole {
    fn from(role: Role) -> Self {
        match role {
            Role::Control => NodeRole::Control,
            Role::Edge => NodeRole::Edge,
        }
    }
}

/// Transport protocol selection for the CLI, maps to `Protocol` from mesh-proto.
#[derive(Debug, Clone, Copy, Default, ValueEnum)]
enum TransportProtocol {
    #[default]
    Tcp,
    Unix,
}

impl std::fmt::Display for TransportProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Tcp => write!(f, "tcp"),
            Self::Unix => write!(f, "unix"),
        }
    }
}

impl From<TransportProtocol> for Protocol {
    fn from(p: TransportProtocol) -> Self {
        match p {
            TransportProtocol::Tcp => Protocol::Tcp,
            TransportProtocol::Unix => Protocol::Unix,
        }
    }
}

/// Health check mode selection for the CLI, maps to `HealthCheckMode` from mesh-proto.
#[derive(Debug, Clone, Copy, ValueEnum)]
enum HealthCheckModeArg {
    TcpConnect,
    UnixConnect,
    HttpGet,
}

impl From<HealthCheckModeArg> for HealthCheckMode {
    fn from(m: HealthCheckModeArg) -> Self {
        match m {
            HealthCheckModeArg::TcpConnect => HealthCheckMode::TcpConnect,
            HealthCheckModeArg::UnixConnect => HealthCheckMode::UnixConnect,
            HealthCheckModeArg::HttpGet => HealthCheckMode::HttpGet,
        }
    }
}

/// Output format for the `status` subcommand.
#[derive(Debug, Clone, Copy, Default, ValueEnum)]
enum OutputFormat {
    #[default]
    Text,
    Json,
}

impl std::fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Text => write!(f, "text"),
            Self::Json => write!(f, "json"),
        }
    }
}

/// Entry point — synchronous so `start` can fork() before any threads exist.
fn main() -> Result<()> {
    let Cli { config, command } = Cli::parse();

    match command {
        Command::Start { role } => {
            // All pre-fork work is synchronous (single-threaded).
            let mut cfg = MeshConfig::load(&config)?;
            cfg.role = role.into();

            let pid_path = cfg.data_dir.join("daemon.pid");
            let socket_path = cfg.data_dir.join("daemon.sock");

            mesh_core::process::cleanup_stale_socket(&socket_path, &pid_path);
            let startup_ready = mesh_core::process::daemonize()?;

            // Acquire PID lock — keep handle alive for daemon lifetime.
            let _pid_lock = mesh_core::process::write_pid_file(&pid_path)?;

            // NOW create tokio runtime (safe: we are the only thread).
            tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()?
                .block_on(async {
                    tracing_subscriber::fmt()
                        .with_env_filter(EnvFilter::from_default_env())
                        .init();

                    let mut daemon = mesh_core::Daemon::new(cfg, config, startup_ready);
                    daemon.run().await
                })
        }
        other => {
            // Non-start commands: create runtime normally.
            tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()?
                .block_on(async move {
                    tracing_subscriber::fmt()
                        .with_env_filter(EnvFilter::from_default_env())
                        .init();

                    match other {
                        Command::Stop => cmd_stop(&config).await,
                        Command::Status { output } => cmd_status(&config, output).await,
                        Command::Expose {
                            name,
                            addr,
                            protocol,
                            health_check_mode,
                            health_check_target,
                        } => {
                            cmd_expose(
                                &config,
                                name,
                                addr,
                                protocol,
                                health_check_mode,
                                health_check_target,
                            )
                            .await
                        }
                        Command::Accept { ticket, name } => cmd_accept(&config, ticket, name).await,
                        Command::Start { .. } => unreachable!(),
                    }
                })
        }
    }
}

/// Stop the running daemon by sending SIGTERM via PID file.
async fn cmd_stop(config_path: &Path) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let pid_path = config.data_dir.join("daemon.pid");

    let pid = mesh_core::process::stop_daemon(&pid_path)?;
    println!("Shutdown signal sent to daemon (PID {pid})");

    for _ in 0..30 {
        if !pid_path.exists() {
            println!("Daemon exited");
            return Ok(());
        }
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }

    println!("Shutdown signal sent; daemon may still be cleaning up");
    Ok(())
}

/// Query daemon status via IPC and print the result.
async fn cmd_status(config_path: &Path, output: OutputFormat) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let socket_path = config.data_dir.join("daemon.sock");

    let mut stream = match tokio::net::UnixStream::connect(&socket_path).await {
        Ok(s) => s,
        Err(_) => {
            println!("Daemon is not running");
            return Ok(());
        }
    };

    mesh_proto::frame::write_json(&mut stream, &IpcRequest::Status)
        .await
        .context("failed to send status request")?;

    let response: IpcResponse = mesh_proto::frame::read_json(&mut stream)
        .await
        .context("failed to read status response")?;

    match response {
        IpcResponse::Status(info) => match output {
            OutputFormat::Text => {
                println!("Role:            {}", info.role);
                println!("Node:            {}", info.node_name);
                println!("Endpoint:        {}", info.endpoint_id);
                println!("Online:          {}", info.online);
                println!("Connected nodes: {}", info.connected_nodes.len());
                println!("Services:        {}", info.services.len());
            }
            OutputFormat::Json => {
                println!(
                    "{}",
                    serde_json::to_string_pretty(&info)
                        .context("failed to serialize status to JSON")?
                );
            }
        },
        IpcResponse::Error { message } => {
            anyhow::bail!("daemon returned error: {message}");
        }
        IpcResponse::Ok { message } => {
            println!("{message}");
        }
        IpcResponse::ServiceExposed {
            name,
            assigned_port,
        } => {
            println!("Service '{name}' exposed (port: {assigned_port:?})");
        }
    }

    Ok(())
}

/// Expose a local service to the mesh via IPC.
async fn cmd_expose(
    config_path: &Path,
    name: String,
    addr: String,
    protocol: TransportProtocol,
    health_check_mode: Option<HealthCheckModeArg>,
    health_check_target: Option<String>,
) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let socket_path = config.data_dir.join("daemon.sock");

    let health_check = health_check_mode.map(|mode| HealthCheckConfig {
        mode: mode.into(),
        target: health_check_target,
        ..HealthCheckConfig::default()
    });

    let request = IpcRequest::ExposeService {
        name: name.clone(),
        local_addr: addr,
        protocol: protocol.into(),
        health_check,
    };

    let mut stream = tokio::net::UnixStream::connect(&socket_path)
        .await
        .context("failed to connect to daemon (is it running?)")?;

    mesh_proto::frame::write_json(&mut stream, &request)
        .await
        .context("failed to send expose request")?;

    let response: IpcResponse = mesh_proto::frame::read_json(&mut stream)
        .await
        .context("failed to read expose response")?;

    match response {
        IpcResponse::ServiceExposed {
            name,
            assigned_port,
        } => {
            if let Some(port) = assigned_port {
                println!("Service '{name}' exposed on port {port}");
            } else {
                println!("Service '{name}' exposed (port pending assignment)");
            }
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("expose failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

/// Accept an edge node's join ticket via IPC (control node only).
async fn cmd_accept(config_path: &Path, ticket: String, _name: Option<String>) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let socket_path = config.data_dir.join("daemon.sock");

    let request = IpcRequest::AcceptNode { ticket };

    let mut stream = tokio::net::UnixStream::connect(&socket_path)
        .await
        .context("failed to connect to daemon (is it running?)")?;

    mesh_proto::frame::write_json(&mut stream, &request)
        .await
        .context("failed to send accept request")?;

    let response: IpcResponse = mesh_proto::frame::read_json(&mut stream)
        .await
        .context("failed to read accept response")?;

    match response {
        IpcResponse::Ok { message } => {
            println!("{message}");
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("accept failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cli_accepts_global_config_for_start() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "start",
            "--role",
            "edge",
            "--config",
            "/tmp/mesh.toml",
        ])
        .unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(cli.command, Command::Start { role: Role::Edge }));
    }

    #[test]
    fn test_cli_accepts_global_config_for_stop() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "stop", "--config", "/tmp/mesh.toml"]).unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(cli.command, Command::Stop));
    }

    #[test]
    fn test_cli_accepts_global_config_for_status() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "status", "--config", "/tmp/mesh.toml"]).unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(
            cli.command,
            Command::Status {
                output: OutputFormat::Text
            }
        ));
    }

    #[test]
    fn test_cli_expose_required_args() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "expose",
            "--name",
            "my-svc",
            "--addr",
            "127.0.0.1:8080",
        ])
        .unwrap();

        match cli.command {
            Command::Expose {
                name,
                addr,
                protocol,
                health_check_mode,
                health_check_target,
            } => {
                assert_eq!(name, "my-svc");
                assert_eq!(addr, "127.0.0.1:8080");
                assert!(matches!(protocol, TransportProtocol::Tcp));
                assert!(health_check_mode.is_none());
                assert!(health_check_target.is_none());
            }
            other => panic!("expected Expose, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_expose_with_health_check() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "expose",
            "--name",
            "web",
            "--addr",
            "127.0.0.1:3000",
            "--protocol",
            "tcp",
            "--health-check-mode",
            "http-get",
            "--health-check-target",
            "http://127.0.0.1:3000/health",
        ])
        .unwrap();

        match cli.command {
            Command::Expose {
                health_check_mode,
                health_check_target,
                ..
            } => {
                assert!(matches!(
                    health_check_mode,
                    Some(HealthCheckModeArg::HttpGet)
                ));
                assert_eq!(
                    health_check_target.as_deref(),
                    Some("http://127.0.0.1:3000/health")
                );
            }
            other => panic!("expected Expose, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_expose_missing_name_fails() {
        let result = Cli::try_parse_from(["mesh-proxy", "expose", "--addr", "127.0.0.1:8080"]);
        assert!(result.is_err(), "expose without --name should fail");
    }

    #[test]
    fn test_cli_accept_ticket_is_positional() {
        let cli = Cli::try_parse_from(["mesh-proxy", "accept", "some-ticket-string"]).unwrap();

        match cli.command {
            Command::Accept { ticket, name } => {
                assert_eq!(ticket, "some-ticket-string");
                assert!(name.is_none());
            }
            other => panic!("expected Accept, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_accept_with_name() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "accept", "ticket123", "--name", "node-alpha"])
                .unwrap();

        match cli.command {
            Command::Accept { ticket, name } => {
                assert_eq!(ticket, "ticket123");
                assert_eq!(name.as_deref(), Some("node-alpha"));
            }
            other => panic!("expected Accept, got {other:?}"),
        }
    }
}
