use std::fmt::Write as _;
use std::io::IsTerminal;
use std::path::{Path, PathBuf};
use std::str::FromStr;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use clap::{Parser, Subcommand, ValueEnum};
use mesh_proto::{
    HealthCheckConfig, HealthCheckMode, InviteToken, IpcRequest, IpcResponse, MeshConfig, NodeRole,
    Protocol, validate_local_addr, validate_service_name,
};
use toml_edit::{DocumentMut, value};
use tracing_subscriber::EnvFilter;

#[derive(Parser)]
#[command(
    name = "mesh-proxy",
    about = "Decentralized P2P port forwarding and service discovery",
    version
)]
struct Cli {
    /// Path to config file.
    #[arg(long, global = true, default_value_os_t = MeshConfig::default_config_path())]
    config: PathBuf,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Start the mesh-proxy daemon.
    Start {
        /// Node role: control or edge.
        #[arg(long)]
        role: Role,

        /// Serialized control node endpoint address written to config before startup.
        #[arg(long)]
        control_addr: Option<String>,
    },

    /// Restart the daemon using the current config.
    Restart,

    /// Stop the running daemon.
    Stop,

    /// Show daemon status.
    Status {
        /// Output format.
        #[arg(long, default_value_t = OutputFormat::Text)]
        output: OutputFormat,
    },

    /// Expose a local service to the mesh network.
    Expose {
        /// Service name (unique identifier on this node).
        #[arg(long)]
        name: String,

        /// Local address the service listens on (e.g. "127.0.0.1:8080" or "/tmp/foo.sock").
        #[arg(long)]
        addr: String,

        /// Transport protocol.
        #[arg(long, default_value_t = TransportProtocol::Tcp)]
        protocol: TransportProtocol,

        /// Health check mode (tcp_connect, unix_connect, http_get).
        #[arg(long)]
        health_check_mode: Option<HealthCheckModeArg>,

        /// Health check target (overrides addr for probe, e.g. an HTTP URL).
        #[arg(long)]
        health_check_target: Option<String>,
    },

    /// Remove a previously exposed local service from the mesh config.
    Unexpose {
        /// Service name to remove.
        #[arg(long)]
        name: String,
    },

    /// Accept an edge node's join ticket (control node only).
    Accept {
        /// The join ticket generated by the edge node.
        ticket: String,

        /// Optional friendly name for the edge node.
        #[arg(long)]
        name: Option<String>,
    },

    /// Join a mesh network using an invite token from the control node.
    Join {
        /// The invite token from `mesh-proxy invite`.
        token: String,
    },

    /// Generate an invite token for a new edge node (control node only).
    Invite {
        /// Friendly name for the joining node.
        #[arg(long)]
        name: Option<String>,

        /// Token validity duration in seconds (default: 300, max: 3600).
        #[arg(long, default_value = "300")]
        ttl: u64,
    },

    /// Manage per-node service quotas (control node only).
    Quota {
        #[command(subcommand)]
        command: QuotaCommand,
    },
}

#[derive(Debug, Subcommand)]
enum QuotaCommand {
    /// Show quota usage for all accepted nodes.
    Show,
    /// Update the quota limit for a specific node.
    Set { endpoint_id: String, limit: usize },
}

/// Node role selection, maps to `NodeRole` from mesh-proto.
#[derive(Debug, Clone, Copy, ValueEnum)]
enum Role {
    Control,
    Edge,
}

impl From<Role> for NodeRole {
    fn from(role: Role) -> Self {
        match role {
            Role::Control => NodeRole::Control,
            Role::Edge => NodeRole::Edge,
        }
    }
}

/// Transport protocol selection for the CLI, maps to `Protocol` from mesh-proto.
#[derive(Debug, Clone, Copy, Default, ValueEnum)]
enum TransportProtocol {
    #[default]
    Tcp,
    Unix,
}

impl std::fmt::Display for TransportProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Tcp => write!(f, "tcp"),
            Self::Unix => write!(f, "unix"),
        }
    }
}

impl From<TransportProtocol> for Protocol {
    fn from(p: TransportProtocol) -> Self {
        match p {
            TransportProtocol::Tcp => Protocol::Tcp,
            TransportProtocol::Unix => Protocol::Unix,
        }
    }
}

/// Health check mode selection for the CLI, maps to `HealthCheckMode` from mesh-proto.
#[derive(Debug, Clone, Copy, ValueEnum)]
enum HealthCheckModeArg {
    TcpConnect,
    UnixConnect,
    HttpGet,
}

impl From<HealthCheckModeArg> for HealthCheckMode {
    fn from(m: HealthCheckModeArg) -> Self {
        match m {
            HealthCheckModeArg::TcpConnect => HealthCheckMode::TcpConnect,
            HealthCheckModeArg::UnixConnect => HealthCheckMode::UnixConnect,
            HealthCheckModeArg::HttpGet => HealthCheckMode::HttpGet,
        }
    }
}

/// Output format for the `status` subcommand.
#[derive(Debug, Clone, Copy, Default, ValueEnum)]
enum OutputFormat {
    #[default]
    Text,
    Json,
}

impl std::fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Text => write!(f, "text"),
            Self::Json => write!(f, "json"),
        }
    }
}

/// Entry point — synchronous so `start` can fork() before any threads exist.
fn main() -> Result<()> {
    let Cli { config, command } = Cli::parse();

    match command {
        Command::Start { role, control_addr } => cmd_start(&config, Some(role), control_addr),
        Command::Restart => cmd_restart(&config),
        Command::Join { token } => cmd_join(&config, token),
        other => {
            // Non-start commands: create runtime normally.
            tokio::runtime::Builder::new_multi_thread()
                .enable_all()
                .build()?
                .block_on(async move {
                    tracing_subscriber::fmt()
                        .with_env_filter(EnvFilter::from_default_env())
                        .init();

                    match other {
                        Command::Stop => cmd_stop(&config).await,
                        Command::Status { output } => cmd_status(&config, output).await,
                        Command::Expose {
                            name,
                            addr,
                            protocol,
                            health_check_mode,
                            health_check_target,
                        } => {
                            cmd_expose(
                                &config,
                                name,
                                addr,
                                protocol,
                                health_check_mode,
                                health_check_target,
                            )
                            .await
                        }
                        Command::Unexpose { name } => cmd_unexpose(&config, name).await,
                        Command::Accept { ticket, name } => cmd_accept(&config, ticket, name).await,
                        Command::Invite { name, ttl } => cmd_invite(&config, name, ttl).await,
                        Command::Quota { command } => cmd_quota(&config, command).await,
                        Command::Start { .. } | Command::Restart | Command::Join { .. } => {
                            unreachable!()
                        }
                    }
                })
        }
    }
}

fn cmd_start(
    config_path: &Path,
    role_override: Option<Role>,
    control_addr_override: Option<String>,
) -> Result<()> {
    // All pre-fork work is synchronous (single-threaded).
    if let Some(control_addr) = control_addr_override.as_deref() {
        write_control_addr_override(config_path, control_addr)?;
    }

    let mut config = MeshConfig::load(config_path)?;
    if let Some(role) = role_override {
        config.role = role.into();
    }

    let pid_path = config.data_dir.join("daemon.pid");
    let socket_path = config.data_dir.join("daemon.sock");

    mesh_core::process::cleanup_stale_socket(&socket_path, &pid_path);
    let startup_ready = mesh_core::process::daemonize()?;

    // Acquire PID lock — keep handle alive for daemon lifetime.
    let _pid_lock = mesh_core::process::write_pid_file(&pid_path)?;

    // Create the runtime after fork so the daemon starts single-threaded.
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?
        .block_on(async {
            tracing_subscriber::fmt()
                .with_env_filter(EnvFilter::from_default_env())
                .init();

            let mut daemon =
                mesh_core::Daemon::new(config, config_path.to_path_buf(), startup_ready);
            daemon.run().await
        })
}

fn write_control_addr_override(config_path: &Path, control_addr: &str) -> Result<()> {
    let control_addr = control_addr.trim();
    if control_addr.is_empty() {
        anyhow::bail!("control address must not be empty");
    }

    MeshConfig::load(config_path)?;

    let content = std::fs::read_to_string(config_path)
        .with_context(|| format!("failed to read config at {}", config_path.display()))?;
    let mut document = DocumentMut::from_str(&content)
        .with_context(|| format!("failed to parse config at {}", config_path.display()))?;
    document["control_addr"] = value(control_addr);

    write_config_document_atomic(config_path, &document)
}

fn write_config_document_atomic(path: &Path, document: &DocumentMut) -> Result<()> {
    let content = document.to_string();

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create config dir {}", parent.display()))?;
    }

    let tmp_path = path.with_extension("toml.tmp");
    let mut open_options = std::fs::OpenOptions::new();
    open_options.create(true).truncate(true).write(true);

    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;

        open_options.mode(0o600);
    }

    let mut file = open_options
        .open(&tmp_path)
        .with_context(|| format!("failed to create temp config at {}", tmp_path.display()))?;
    std::io::Write::write_all(&mut file, content.as_bytes())
        .with_context(|| format!("failed to write temp config at {}", tmp_path.display()))?;
    file.sync_all()
        .with_context(|| format!("failed to fsync temp config at {}", tmp_path.display()))?;

    std::fs::rename(&tmp_path, path).with_context(|| {
        format!(
            "failed to rename {} to {}",
            tmp_path.display(),
            path.display()
        )
    })?;

    Ok(())
}

fn cmd_restart(config_path: &Path) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let pid_path = config.data_dir.join("daemon.pid");

    match mesh_core::process::stop_daemon(&pid_path) {
        Ok(pid) => {
            println!("Shutdown signal sent to daemon (PID {pid})");

            if wait_for_pid_file_removal(&pid_path, Duration::from_secs(10)) {
                println!("Daemon exited");
            } else if pid_path.exists() {
                let stuck_pid = read_pid_file(&pid_path)?;
                send_signal(stuck_pid, libc::SIGKILL)?;
                println!(
                    "Daemon did not exit within 10s; sent SIGKILL to daemon (PID {stuck_pid})"
                );
                let _ = wait_for_process_exit(stuck_pid, Duration::from_secs(2));
            }
        }
        Err(error) => {
            if mesh_core::process::is_daemon_running(&pid_path) {
                return Err(error);
            }
            println!("Daemon not running; starting a new instance");
        }
    }

    cmd_start(config_path, None, None)
}

fn cmd_join(config_path: &Path, token_str: String) -> Result<()> {
    let token = InviteToken::from_bs58(&token_str)
        .context("failed to decode invite token (is it copy-pasted correctly?)")?;
    token.validate().context("invite token validation failed")?;

    let node_name = token.node_name.clone().unwrap_or_else(|| {
        hostname::get()
            .map(|h| h.to_string_lossy().into_owned())
            .unwrap_or_else(|_| "unnamed".to_string())
    });

    // Write config: role=edge, control_addr, node_name
    let content = if config_path.exists() {
        std::fs::read_to_string(config_path)
            .with_context(|| format!("failed to read config at {}", config_path.display()))?
    } else {
        // Bootstrap a minimal config so toml_edit has something to work with.
        String::new()
    };
    let mut document = DocumentMut::from_str(&content)
        .with_context(|| format!("failed to parse config at {}", config_path.display()))?;
    document["role"] = value("edge");
    document["control_addr"] = value(&token.control_addr);
    document["node_name"] = value(&node_name);
    write_config_document_atomic(config_path, &document)?;

    // Save invite nonce for the daemon's first registration (single-use).
    let config = MeshConfig::load(config_path)?;
    let nonce_path = config.data_dir.join("invite_nonce.txt");
    write_nonce_file(&nonce_path, &token.nonce)?;

    println!("Joining mesh as '{node_name}'...");
    cmd_start(config_path, Some(Role::Edge), None)?;
    println!("Use `mesh-proxy status` to verify connection.");
    Ok(())
}

/// Write the invite nonce to a file with restricted permissions (0o600).
fn write_nonce_file(path: &Path, nonce: &[u8; 16]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create data dir {}", parent.display()))?;
    }

    let encoded = bs58::encode(nonce).into_string();

    let mut open_options = std::fs::OpenOptions::new();
    open_options.create(true).truncate(true).write(true);

    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        open_options.mode(0o600);
    }

    let mut file = open_options
        .open(path)
        .with_context(|| format!("failed to create nonce file at {}", path.display()))?;
    std::io::Write::write_all(&mut file, encoded.as_bytes())
        .with_context(|| format!("failed to write nonce file at {}", path.display()))?;
    file.sync_all()
        .with_context(|| format!("failed to fsync nonce file at {}", path.display()))?;

    Ok(())
}

fn read_pid_file(pid_path: &Path) -> Result<libc::pid_t> {
    std::fs::read_to_string(pid_path)
        .with_context(|| format!("failed to read PID file {}", pid_path.display()))?
        .trim()
        .parse()
        .context("invalid PID in file")
}

fn wait_for_pid_file_removal(pid_path: &Path, timeout: Duration) -> bool {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if !pid_path.exists() {
            return true;
        }
        std::thread::sleep(Duration::from_millis(200));
    }
    !pid_path.exists()
}

fn wait_for_process_exit(pid: libc::pid_t, timeout: Duration) -> bool {
    let deadline = Instant::now() + timeout;
    while Instant::now() < deadline {
        if !process_exists(pid) {
            return true;
        }
        std::thread::sleep(Duration::from_millis(200));
    }
    !process_exists(pid)
}

fn process_exists(pid: libc::pid_t) -> bool {
    // SAFETY: signal 0 only checks whether the target process exists.
    let rc = unsafe { libc::kill(pid, 0) };
    if rc == 0 {
        return true;
    }

    matches!(
        std::io::Error::last_os_error().raw_os_error(),
        Some(libc::EPERM)
    )
}

fn send_signal(pid: libc::pid_t, signal: i32) -> Result<()> {
    // SAFETY: sending a signal to a PID read from the daemon PID file.
    let rc = unsafe { libc::kill(pid, signal) };
    if rc == 0 {
        return Ok(());
    }

    let error = std::io::Error::last_os_error();
    if error.raw_os_error() == Some(libc::ESRCH) {
        return Ok(());
    }

    anyhow::bail!("failed to send signal {signal} to PID {pid}: {error}");
}

/// Stop the running daemon by sending SIGTERM via PID file.
async fn cmd_stop(config_path: &Path) -> Result<()> {
    let config = MeshConfig::load(config_path)?;
    let pid_path = config.data_dir.join("daemon.pid");

    let pid = mesh_core::process::stop_daemon(&pid_path)?;
    println!("Shutdown signal sent to daemon (PID {pid})");

    for _ in 0..30 {
        if !pid_path.exists() {
            println!("Daemon exited");
            return Ok(());
        }
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    }

    println!("Shutdown signal sent; daemon may still be cleaning up");
    Ok(())
}

fn daemon_socket_path(config_path: &Path) -> Result<PathBuf> {
    let config = MeshConfig::load(config_path)?;
    Ok(config.data_dir.join("daemon.sock"))
}

async fn send_ipc_request(
    socket_path: &Path,
    request: &IpcRequest,
    operation: &str,
) -> Result<IpcResponse> {
    let mut stream = tokio::net::UnixStream::connect(socket_path)
        .await
        .with_context(|| format!("failed to connect to daemon for {operation}"))?;

    mesh_proto::frame::write_json(&mut stream, request)
        .await
        .with_context(|| format!("failed to send {operation} request"))?;

    mesh_proto::frame::read_json(&mut stream)
        .await
        .with_context(|| format!("failed to read {operation} response"))
}

/// Query daemon status via IPC and print the result.
async fn cmd_status(config_path: &Path, output: OutputFormat) -> Result<()> {
    let socket_path = daemon_socket_path(config_path)?;

    let mut stream = match tokio::net::UnixStream::connect(&socket_path).await {
        Ok(s) => s,
        Err(error)
            if matches!(
                error.kind(),
                std::io::ErrorKind::NotFound | std::io::ErrorKind::ConnectionRefused
            ) =>
        {
            println!(
                "{} daemon not running",
                format_indicator("OFFLINE", stdout_supports_color())
            );
            return Ok(());
        }
        Err(error) => return Err(error).context("failed to connect to daemon for status"),
    };

    mesh_proto::frame::write_json(&mut stream, &IpcRequest::Status)
        .await
        .context("failed to send status request")?;

    let response: IpcResponse = mesh_proto::frame::read_json(&mut stream)
        .await
        .context("failed to read status response")?;

    match response {
        IpcResponse::Status(info) => match output {
            OutputFormat::Text => {
                println!("{}", render_status_text(&info, stdout_supports_color()));
            }
            OutputFormat::Json => {
                println!(
                    "{}",
                    serde_json::to_string_pretty(&info)
                        .context("failed to serialize status to JSON")?
                );
            }
        },
        IpcResponse::Error { message } => {
            anyhow::bail!("daemon returned error: {message}");
        }
        IpcResponse::Ok { message } => {
            println!("{message}");
        }
        IpcResponse::Reloaded => {
            println!("Configuration reloaded");
        }
        IpcResponse::ServiceExposed {
            name,
            assigned_port,
        } => {
            println!("Service '{name}' exposed on port {assigned_port}");
        }
        IpcResponse::ServiceExposeTimedOut {
            name,
            timeout_seconds,
        } => {
            println!(
                "Service '{name}' saved, but port assignment did not arrive within {timeout_seconds}s"
            );
        }
        IpcResponse::ServiceUnexposed { name } => {
            println!("Service '{name}' unexposed");
        }
        IpcResponse::ListenerStatus { port, state } => {
            println!("Listener {port}: {state:?}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

/// Remove a local service from the mesh via IPC.
async fn cmd_unexpose(config_path: &Path, name: String) -> Result<()> {
    if let Err(reason) = validate_service_name(&name) {
        anyhow::bail!("invalid service name '{name}': {reason}");
    }

    let request = IpcRequest::UnexposeService { name: name.clone() };

    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(&socket_path, &request, "unexpose").await?;

    match response {
        IpcResponse::ServiceUnexposed { name } => {
            println!("Service '{name}' unexposed");
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("unexpose failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

/// Expose a local service to the mesh via IPC.
async fn cmd_expose(
    config_path: &Path,
    name: String,
    addr: String,
    protocol: TransportProtocol,
    health_check_mode: Option<HealthCheckModeArg>,
    health_check_target: Option<String>,
) -> Result<()> {
    if let Err(reason) = validate_service_name(&name) {
        anyhow::bail!("invalid service name '{name}': {reason}");
    }
    if let Err(reason) = validate_local_addr(&addr) {
        anyhow::bail!("invalid local address '{addr}': {reason}");
    }

    let health_check = health_check_mode.map(|mode| HealthCheckConfig {
        mode: mode.into(),
        target: health_check_target,
        ..HealthCheckConfig::default()
    });

    let request = IpcRequest::ExposeService {
        name: name.clone(),
        local_addr: addr,
        protocol: protocol.into(),
        health_check,
    };

    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(&socket_path, &request, "expose").await?;

    match response {
        IpcResponse::ServiceExposed {
            name,
            assigned_port,
        } => {
            println!("Service '{name}' exposed on port {assigned_port}");
        }
        IpcResponse::ServiceExposeTimedOut {
            name,
            timeout_seconds,
        } => {
            anyhow::bail!(
                "service '{name}' saved, but the control node did not assign a port within {timeout_seconds}s"
            );
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("expose failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

/// Accept an edge node's join ticket via IPC (control node only).
async fn cmd_accept(config_path: &Path, ticket: String, name: Option<String>) -> Result<()> {
    let request = IpcRequest::AcceptNode {
        ticket,
        node_name: name,
    };

    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(&socket_path, &request, "accept").await?;

    match response {
        IpcResponse::Ok { message } => {
            println!("{message}");
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("accept failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

/// Generate an invite token via IPC (control node only).
async fn cmd_invite(config_path: &Path, name: Option<String>, ttl: u64) -> Result<()> {
    let request = IpcRequest::Invite {
        name,
        ttl_seconds: Some(ttl),
    };

    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(&socket_path, &request, "invite").await?;

    match response {
        IpcResponse::InviteResult { token } => {
            println!("Invite token (expires in {ttl}s):");
            println!("{token}");
            println!();
            println!("On the new node, run:");
            println!("  mesh-proxy join {token}");
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("invite failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

async fn cmd_quota(config_path: &Path, command: QuotaCommand) -> Result<()> {
    match command {
        QuotaCommand::Show => cmd_quota_show(config_path).await,
        QuotaCommand::Set { endpoint_id, limit } => {
            cmd_quota_set(config_path, endpoint_id, limit).await
        }
    }
}

async fn cmd_quota_show(config_path: &Path) -> Result<()> {
    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(&socket_path, &IpcRequest::QuotaShow, "quota show").await?;

    match response {
        IpcResponse::QuotaInfo { quotas } => {
            println!("{}", render_quota_table(&quotas));
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("quota show failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

async fn cmd_quota_set(config_path: &Path, endpoint_id: String, limit: usize) -> Result<()> {
    let socket_path = daemon_socket_path(config_path)?;
    let response = send_ipc_request(
        &socket_path,
        &IpcRequest::QuotaSet {
            endpoint_id: endpoint_id.clone(),
            limit,
        },
        "quota set",
    )
    .await?;

    match response {
        IpcResponse::QuotaUpdated => {
            println!("Quota for {endpoint_id} updated to {limit}");
        }
        IpcResponse::Error { message } => {
            anyhow::bail!("quota set failed: {message}");
        }
        other => {
            anyhow::bail!("unexpected response: {other:?}");
        }
    }

    Ok(())
}

fn render_status_text(info: &mesh_proto::StatusInfo, color_enabled: bool) -> String {
    let mut output = String::new();
    let daemon_state = if info.online { "ONLINE" } else { "OFFLINE" };
    let role = info.role.to_ascii_lowercase();

    let _ = writeln!(
        &mut output,
        "{} {} ({role})",
        format_indicator(daemon_state, color_enabled),
        info.node_name
    );
    let _ = writeln!(&mut output, "Endpoint: {}", info.endpoint_id);
    if let Some(addr) = &info.endpoint_addr {
        let _ = writeln!(&mut output, "Connect Addr: {addr}");
    }
    let _ = writeln!(
        &mut output,
        "Peers: {}  Services: {}  Routes: {}",
        info.peer_count,
        info.services.len(),
        info.route_table_version
    );

    if let Some(health_bind) = &info.health_bind {
        let _ = writeln!(&mut output, "Health: {health_bind}");
    }

    let services = sorted_services(&info.services);
    if services.is_empty() {
        let _ = write!(&mut output, "No services");
        return output;
    }

    for service in services {
        let _ = writeln!(
            &mut output,
            "{}",
            render_service_line(service, color_enabled)
        );
    }

    output.trim_end().to_string()
}

fn render_service_line(service: &mesh_proto::ServiceStatus, color_enabled: bool) -> String {
    format!(
        "{} {} ({}) -> {}",
        format_indicator(service_status_label(service.status), color_enabled),
        service.name,
        service.node_name,
        format_service_target(service.assigned_port)
    )
}

fn sorted_services(services: &[mesh_proto::ServiceStatus]) -> Vec<&mesh_proto::ServiceStatus> {
    let mut services = services.iter().collect::<Vec<_>>();
    services.sort_by(|left, right| {
        left.assigned_port
            .unwrap_or(u16::MAX)
            .cmp(&right.assigned_port.unwrap_or(u16::MAX))
            .then_with(|| left.node_name.cmp(&right.node_name))
            .then_with(|| left.name.cmp(&right.name))
    });
    services
}

fn service_status_label(status: mesh_proto::ServiceDisplayStatus) -> &'static str {
    match status {
        mesh_proto::ServiceDisplayStatus::Healthy => "ONLINE",
        mesh_proto::ServiceDisplayStatus::Degraded => "DEGRADED",
        mesh_proto::ServiceDisplayStatus::Unhealthy => "OFFLINE",
        mesh_proto::ServiceDisplayStatus::Unknown => "UNKNOWN",
        mesh_proto::ServiceDisplayStatus::Ok => "OK",
        mesh_proto::ServiceDisplayStatus::Unreachable => "UNREACHABLE",
        mesh_proto::ServiceDisplayStatus::Routed => "ROUTED",
    }
}

fn format_service_target(port: Option<u16>) -> String {
    match port {
        Some(port) => format!(":{port}"),
        None => "pending".to_string(),
    }
}

fn format_indicator(label: &str, color_enabled: bool) -> String {
    if !color_enabled {
        return format!("[{label}]");
    }

    let color_code = match label {
        "ONLINE" => "32",
        "OK" => "32",
        "ROUTED" => "36",
        "DEGRADED" | "UNKNOWN" => "33",
        "OFFLINE" | "UNREACHABLE" => "31",
        _ => "0",
    };

    format!("\u{1b}[{color_code}m[{label}]\u{1b}[0m")
}

fn stdout_supports_color() -> bool {
    std::io::stdout().is_terminal()
}

fn render_quota_table(quotas: &[(String, usize, usize)]) -> String {
    if quotas.is_empty() {
        return "No accepted nodes".to_string();
    }

    let endpoint_width = quotas
        .iter()
        .map(|(endpoint_id, _, _)| endpoint_id.len())
        .max()
        .unwrap_or(0)
        .max("ENDPOINT ID".len());
    let used_width = quotas
        .iter()
        .map(|(_, used, _)| used.to_string().len())
        .max()
        .unwrap_or(0)
        .max("USED".len());
    let limit_width = quotas
        .iter()
        .map(|(_, _, limit)| limit.to_string().len())
        .max()
        .unwrap_or(0)
        .max("LIMIT".len());

    let mut output = String::new();
    let _ = writeln!(
        &mut output,
        "{:<endpoint_width$} {:>used_width$} {:>limit_width$}",
        "ENDPOINT ID",
        "USED",
        "LIMIT",
        endpoint_width = endpoint_width,
        used_width = used_width,
        limit_width = limit_width,
    );

    for (endpoint_id, used, limit) in quotas {
        let _ = writeln!(
            &mut output,
            "{:<endpoint_width$} {:>used_width$} {:>limit_width$}",
            endpoint_id,
            used,
            limit,
            endpoint_width = endpoint_width,
            used_width = used_width,
            limit_width = limit_width,
        );
    }

    output.trim_end().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cli_accepts_global_config_for_start() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "start",
            "--role",
            "edge",
            "--config",
            "/tmp/mesh.toml",
        ])
        .unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(
            cli.command,
            Command::Start {
                role: Role::Edge,
                control_addr: None
            }
        ));
    }

    #[test]
    fn test_cli_accepts_global_config_for_stop() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "stop", "--config", "/tmp/mesh.toml"]).unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(cli.command, Command::Stop));
    }

    #[test]
    fn test_cli_accepts_global_config_for_status() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "status", "--config", "/tmp/mesh.toml"]).unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(
            cli.command,
            Command::Status {
                output: OutputFormat::Text
            }
        ));
    }

    #[test]
    fn test_cli_accepts_global_config_for_restart() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "restart", "--config", "/tmp/mesh.toml"]).unwrap();

        assert_eq!(cli.config, PathBuf::from("/tmp/mesh.toml"));
        assert!(matches!(cli.command, Command::Restart));
    }

    #[test]
    fn test_cli_accepts_quota_show_subcommand() {
        let cli = Cli::try_parse_from(["mesh-proxy", "quota", "show"]).unwrap();

        assert!(matches!(
            cli.command,
            Command::Quota {
                command: QuotaCommand::Show
            }
        ));
    }

    #[test]
    fn test_cli_accepts_quota_set_subcommand() {
        let cli = Cli::try_parse_from(["mesh-proxy", "quota", "set", "ep-123", "7"]).unwrap();

        match cli.command {
            Command::Quota {
                command: QuotaCommand::Set { endpoint_id, limit },
            } => {
                assert_eq!(endpoint_id, "ep-123");
                assert_eq!(limit, 7);
            }
            other => panic!("expected Quota::Set, got {other:?}"),
        }
    }

    #[test]
    fn test_render_status_text_formats_compact_service_lines() {
        let info = mesh_proto::StatusInfo {
            role: "Control".to_string(),
            node_name: "controller".to_string(),
            endpoint_id: "ep-ctrl".to_string(),
            endpoint_addr: Some(r#"{"node_id":"ep-ctrl"}"#.to_string()),
            online: true,
            peer_count: 1,
            connected_nodes: vec![mesh_proto::ConnectedNode {
                name: "edge-1".to_string(),
                endpoint_id: "ep-edge".to_string(),
                online: true,
            }],
            services: vec![
                mesh_proto::ServiceStatus {
                    name: "api".to_string(),
                    node_name: "node-beta".to_string(),
                    assigned_port: Some(40001),
                    status: mesh_proto::ServiceDisplayStatus::Routed,
                },
                mesh_proto::ServiceStatus {
                    name: "web".to_string(),
                    node_name: "node-alpha".to_string(),
                    assigned_port: Some(40000),
                    status: mesh_proto::ServiceDisplayStatus::Ok,
                },
            ],
            health_bind: Some("127.0.0.1:49000".to_string()),
            route_table_version: 3,
        };

        let rendered = render_status_text(&info, false);

        assert!(rendered.contains("[ONLINE] controller (control)"));
        assert!(rendered.contains(r#"Connect Addr: {"node_id":"ep-ctrl"}"#));
        assert!(rendered.contains("Peers: 1  Services: 2  Routes: 3"));
        assert!(rendered.contains("[OK] web (node-alpha) -> :40000"));
        assert!(rendered.contains("[ROUTED] api (node-beta) -> :40001"));
    }

    #[test]
    fn test_render_quota_table_includes_headers_and_values() {
        let rendered = render_quota_table(&[
            ("ep-1".to_string(), 1, 5),
            ("ep-very-long".to_string(), 2, 10),
        ]);

        assert!(rendered.contains("ENDPOINT ID"));
        assert!(rendered.contains("ep-1"));
        assert!(rendered.contains("ep-very-long"));
        assert!(rendered.contains("10"));
    }

    #[test]
    fn test_cli_expose_required_args() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "expose",
            "--name",
            "my-svc",
            "--addr",
            "127.0.0.1:8080",
        ])
        .unwrap();

        match cli.command {
            Command::Expose {
                name,
                addr,
                protocol,
                health_check_mode,
                health_check_target,
            } => {
                assert_eq!(name, "my-svc");
                assert_eq!(addr, "127.0.0.1:8080");
                assert!(matches!(protocol, TransportProtocol::Tcp));
                assert!(health_check_mode.is_none());
                assert!(health_check_target.is_none());
            }
            other => panic!("expected Expose, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_start_accepts_control_addr() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "start",
            "--role",
            "edge",
            "--control-addr",
            r#"{"node_id":"ep-ctrl"}"#,
        ])
        .unwrap();

        match cli.command {
            Command::Start { role, control_addr } => {
                assert!(matches!(role, Role::Edge));
                assert_eq!(control_addr.as_deref(), Some(r#"{"node_id":"ep-ctrl"}"#));
            }
            other => panic!("expected Start, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_expose_with_health_check() {
        let cli = Cli::try_parse_from([
            "mesh-proxy",
            "expose",
            "--name",
            "web",
            "--addr",
            "127.0.0.1:3000",
            "--protocol",
            "tcp",
            "--health-check-mode",
            "http-get",
            "--health-check-target",
            "http://127.0.0.1:3000/health",
        ])
        .unwrap();

        match cli.command {
            Command::Expose {
                health_check_mode,
                health_check_target,
                ..
            } => {
                assert!(matches!(
                    health_check_mode,
                    Some(HealthCheckModeArg::HttpGet)
                ));
                assert_eq!(
                    health_check_target.as_deref(),
                    Some("http://127.0.0.1:3000/health")
                );
            }
            other => panic!("expected Expose, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_expose_missing_name_fails() {
        let result = Cli::try_parse_from(["mesh-proxy", "expose", "--addr", "127.0.0.1:8080"]);
        assert!(result.is_err(), "expose without --name should fail");
    }

    #[test]
    fn test_cli_unexpose_required_args() {
        let cli = Cli::try_parse_from(["mesh-proxy", "unexpose", "--name", "my-svc"]).unwrap();

        match cli.command {
            Command::Unexpose { name } => {
                assert_eq!(name, "my-svc");
            }
            other => panic!("expected Unexpose, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_unexpose_missing_name_fails() {
        let result = Cli::try_parse_from(["mesh-proxy", "unexpose"]);
        assert!(result.is_err(), "unexpose without --name should fail");
    }

    #[test]
    fn test_cli_accept_ticket_is_positional() {
        let cli = Cli::try_parse_from(["mesh-proxy", "accept", "some-ticket-string"]).unwrap();

        match cli.command {
            Command::Accept { ticket, name } => {
                assert_eq!(ticket, "some-ticket-string");
                assert!(name.is_none());
            }
            other => panic!("expected Accept, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_accept_with_name() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "accept", "ticket123", "--name", "node-alpha"])
                .unwrap();

        match cli.command {
            Command::Accept { ticket, name } => {
                assert_eq!(ticket, "ticket123");
                assert_eq!(name.as_deref(), Some("node-alpha"));
            }
            other => panic!("expected Accept, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_invite_defaults() {
        let cli = Cli::try_parse_from(["mesh-proxy", "invite"]).unwrap();

        match cli.command {
            Command::Invite { name, ttl } => {
                assert!(name.is_none());
                assert_eq!(ttl, 300);
            }
            other => panic!("expected Invite, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_invite_with_name_and_ttl() {
        let cli =
            Cli::try_parse_from(["mesh-proxy", "invite", "--name", "worker-1", "--ttl", "600"])
                .unwrap();

        match cli.command {
            Command::Invite { name, ttl } => {
                assert_eq!(name.as_deref(), Some("worker-1"));
                assert_eq!(ttl, 600);
            }
            other => panic!("expected Invite, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_invite_name_only() {
        let cli = Cli::try_parse_from(["mesh-proxy", "invite", "--name", "edge-node"]).unwrap();

        match cli.command {
            Command::Invite { name, ttl } => {
                assert_eq!(name.as_deref(), Some("edge-node"));
                assert_eq!(ttl, 300);
            }
            other => panic!("expected Invite, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_join_token_is_positional() {
        let cli = Cli::try_parse_from(["mesh-proxy", "join", "some-token-string"]).unwrap();

        match cli.command {
            Command::Join { token } => {
                assert_eq!(token, "some-token-string");
            }
            other => panic!("expected Join, got {other:?}"),
        }
    }

    #[test]
    fn test_cli_join_missing_token_fails() {
        let result = Cli::try_parse_from(["mesh-proxy", "join"]);
        assert!(result.is_err(), "join without token should fail");
    }

    #[test]
    fn test_cmd_join_writes_config_and_nonce() {
        use std::time::{SystemTime, UNIX_EPOCH};

        let dir = tempfile::Builder::new()
            .prefix("mesh-join-")
            .tempdir_in("/tmp")
            .unwrap();
        let config_path = dir.path().join("config.toml");
        let data_dir = dir.path().join("data");

        // Pre-create a minimal config so MeshConfig::load points data_dir to our temp.
        let initial_config = format!(
            "node_name = \"old-name\"\nrole = \"control\"\ndata_dir = \"{}\"\n",
            data_dir.display()
        );
        std::fs::write(&config_path, &initial_config).unwrap();

        let token = InviteToken {
            control_addr: r#"{"node_id":"ep-ctrl-abc"}"#.to_string(),
            nonce: [
                10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160,
            ],
            ttl_seconds: 3600,
            created_at: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            node_name: Some("invited-edge".to_string()),
        };
        let encoded = token.to_bs58().unwrap();

        // Decode + validate + write config + write nonce (skip daemon start).
        let decoded = InviteToken::from_bs58(&encoded).unwrap();
        decoded.validate().unwrap();

        let node_name = decoded
            .node_name
            .clone()
            .unwrap_or_else(|| "fallback".to_string());

        let content = std::fs::read_to_string(&config_path).unwrap();
        let mut document = DocumentMut::from_str(&content).unwrap();
        document["role"] = value("edge");
        document["control_addr"] = value(&decoded.control_addr);
        document["node_name"] = value(&node_name);
        write_config_document_atomic(&config_path, &document).unwrap();

        let config = MeshConfig::load(&config_path).unwrap();
        assert_eq!(config.role, NodeRole::Edge);
        assert_eq!(
            config.control_addr.as_deref(),
            Some(r#"{"node_id":"ep-ctrl-abc"}"#)
        );
        assert_eq!(config.node_name, "invited-edge");

        let nonce_path = config.data_dir.join("invite_nonce.txt");
        write_nonce_file(&nonce_path, &decoded.nonce).unwrap();
        assert!(nonce_path.exists());

        let nonce_content = std::fs::read_to_string(&nonce_path).unwrap();
        assert!(!nonce_content.is_empty());

        // Verify nonce roundtrips through bs58.
        let nonce_bytes = bs58::decode(&nonce_content).into_vec().unwrap();
        assert_eq!(nonce_bytes, decoded.nonce);
    }

    #[test]
    fn test_cmd_join_uses_hostname_when_no_node_name() {
        use std::time::{SystemTime, UNIX_EPOCH};

        let token = InviteToken {
            control_addr: "addr-123".to_string(),
            nonce: [1; 16],
            ttl_seconds: 300,
            created_at: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            node_name: None,
        };

        let node_name = token.node_name.clone().unwrap_or_else(|| {
            hostname::get()
                .map(|h| h.to_string_lossy().into_owned())
                .unwrap_or_else(|_| "unnamed".to_string())
        });

        // Should fall back to system hostname, not be empty.
        assert!(!node_name.is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn test_nonce_file_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let dir = tempfile::Builder::new()
            .prefix("mesh-nonce-")
            .tempdir_in("/tmp")
            .unwrap();
        let nonce_path = dir.path().join("invite_nonce.txt");
        let nonce = [42u8; 16];

        write_nonce_file(&nonce_path, &nonce).unwrap();

        let mode = std::fs::metadata(&nonce_path).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o600, "nonce file should be owner-only rw");
    }
}
