use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

/// An invite token generated by the control node for a new edge node to join.
///
/// Unlike `JoinTicket` (edge → control), an `InviteToken` flows from
/// control → edge. It encodes everything an edge node needs to connect
/// and auto-register with a single command.
///
/// Serialized to JSON then bs58-encoded for safe CLI transport.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InviteToken {
    /// Serialized control node endpoint address (the connect addr from `mesh-proxy status`).
    pub control_addr: String,
    /// Random nonce for single-use enforcement (128-bit).
    pub nonce: [u8; 16],
    /// Token validity duration in seconds.
    pub ttl_seconds: u64,
    /// When this token was created (Unix epoch seconds).
    pub created_at: u64,
    /// Optional friendly name for the joining node.
    pub node_name: Option<String>,
}

impl InviteToken {
    /// Returns `true` if the token has expired relative to the current system time.
    pub fn is_expired(&self) -> bool {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        now.saturating_sub(self.created_at) > self.ttl_seconds
    }

    /// Encode the token as a bs58 string (JSON → bs58).
    pub fn to_bs58(&self) -> Result<String, InviteError> {
        let json =
            serde_json::to_vec(self).map_err(|e| InviteError::InvalidEncoding(e.to_string()))?;
        Ok(bs58::encode(json).into_string())
    }

    /// Decode a token from a bs58 string (bs58 → JSON).
    pub fn from_bs58(encoded: &str) -> Result<Self, InviteError> {
        let bytes = bs58::decode(encoded)
            .into_vec()
            .map_err(|e| InviteError::InvalidEncoding(e.to_string()))?;
        let token: Self = serde_json::from_slice(&bytes)
            .map_err(|e| InviteError::InvalidEncoding(e.to_string()))?;
        Ok(token)
    }

    /// Validate the token: check not expired, control_addr not empty, nonce not all zeros.
    pub fn validate(&self) -> Result<(), InviteError> {
        if self.is_expired() {
            return Err(InviteError::Expired);
        }
        if self.control_addr.is_empty() {
            return Err(InviteError::InvalidFields(
                "control_addr must not be empty".to_string(),
            ));
        }
        if self.nonce == [0u8; 16] {
            return Err(InviteError::InvalidFields(
                "nonce must not be all zeros".to_string(),
            ));
        }
        Ok(())
    }
}

/// Errors arising from invite token operations.
#[derive(Debug, Clone, thiserror::Error)]
pub enum InviteError {
    #[error("invite token has expired")]
    Expired,
    #[error("invalid encoding: {0}")]
    InvalidEncoding(String),
    #[error("invalid fields: {0}")]
    InvalidFields(String),
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn now_secs() -> u64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs()
    }

    fn sample_token() -> InviteToken {
        InviteToken {
            control_addr: "endpoint-addr-abc123".to_string(),
            nonce: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
            ttl_seconds: 3600,
            created_at: now_secs(),
            node_name: None,
        }
    }

    #[test]
    fn test_invite_token_roundtrip() {
        let token = sample_token();
        let encoded = token.to_bs58().unwrap();
        let decoded = InviteToken::from_bs58(&encoded).unwrap();
        assert_eq!(token, decoded);
    }

    #[test]
    fn test_invite_token_expired() {
        let token = InviteToken {
            created_at: 1_000_000,
            ttl_seconds: 0,
            ..sample_token()
        };
        assert!(token.is_expired());

        let far_past = InviteToken {
            created_at: 1,
            ttl_seconds: 10,
            ..sample_token()
        };
        assert!(far_past.is_expired());
    }

    #[test]
    fn test_invite_token_not_expired() {
        let token = InviteToken {
            ttl_seconds: 3600,
            created_at: now_secs(),
            ..sample_token()
        };
        assert!(!token.is_expired());
    }

    #[test]
    fn test_invite_token_invalid_bs58() {
        let result = InviteToken::from_bs58("!!!");
        assert!(result.is_err());
        assert!(matches!(result, Err(InviteError::InvalidEncoding(_))));
    }

    #[test]
    fn test_invite_token_empty_control_addr() {
        let token = InviteToken {
            control_addr: String::new(),
            ..sample_token()
        };
        let result = token.validate();
        assert!(matches!(result, Err(InviteError::InvalidFields(_))));
    }

    #[test]
    fn test_invite_token_zero_nonce() {
        let token = InviteToken {
            nonce: [0u8; 16],
            ..sample_token()
        };
        let result = token.validate();
        assert!(matches!(result, Err(InviteError::InvalidFields(_))));
    }

    #[test]
    fn test_invite_token_with_node_name() {
        let with_name = InviteToken {
            node_name: Some("my-edge-node".to_string()),
            ..sample_token()
        };
        let encoded = with_name.to_bs58().unwrap();
        let decoded = InviteToken::from_bs58(&encoded).unwrap();
        assert_eq!(decoded.node_name, Some("my-edge-node".to_string()));

        let without_name = InviteToken {
            node_name: None,
            ..sample_token()
        };
        let encoded = without_name.to_bs58().unwrap();
        let decoded = InviteToken::from_bs58(&encoded).unwrap();
        assert_eq!(decoded.node_name, None);
    }

    #[test]
    fn test_invite_token_validate_success() {
        let token = sample_token();
        assert!(token.validate().is_ok());
    }

    #[test]
    fn test_invite_token_validate_expired() {
        let token = InviteToken {
            created_at: 1,
            ttl_seconds: 1,
            ..sample_token()
        };
        let result = token.validate();
        assert!(matches!(result, Err(InviteError::Expired)));
    }
}
