use serde::{Deserialize, Serialize};

/// A join ticket generated by an edge node and accepted by the control node.
///
/// The ticket is serialized to JSON, then encoded as bs58 for safe transport
/// in CLI arguments and config files.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JoinTicket {
    /// The edge node's endpoint id (public key, hex-encoded).
    pub endpoint_id: String,
    /// Unix timestamp (seconds) when this ticket was created.
    pub created_at: u64,
    /// How long (in seconds) the ticket remains valid after `created_at`.
    pub ttl_seconds: u64,
    /// Random nonce to prevent replay.
    pub nonce: [u8; 16],
}

impl JoinTicket {
    /// Returns `true` if the ticket has expired relative to the given `now` timestamp.
    pub fn is_expired(&self, now: u64) -> bool {
        now.saturating_sub(self.created_at) > self.ttl_seconds
    }

    /// Encode the ticket as a bs58 string (JSON → bs58).
    pub fn to_bs58(&self) -> Result<String, TicketError> {
        let json = serde_json::to_vec(self).map_err(|e| TicketError::Encode(e.to_string()))?;
        Ok(bs58::encode(json).into_string())
    }

    /// Decode a ticket from a bs58 string (bs58 → JSON).
    pub fn from_bs58(encoded: &str) -> Result<Self, TicketError> {
        let bytes = bs58::decode(encoded)
            .into_vec()
            .map_err(|e| TicketError::Decode(e.to_string()))?;
        let ticket: Self =
            serde_json::from_slice(&bytes).map_err(|e| TicketError::Decode(e.to_string()))?;
        Ok(ticket)
    }
}

/// Result of validating a join ticket.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TicketStatus {
    Valid,
    Expired,
    AlreadyUsed,
    EndpointMismatch,
}

/// Errors arising from ticket encoding/decoding.
#[derive(Debug, Clone, thiserror::Error)]
pub enum TicketError {
    #[error("failed to encode ticket: {0}")]
    Encode(String),
    #[error("failed to decode ticket: {0}")]
    Decode(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_ticket() -> JoinTicket {
        JoinTicket {
            endpoint_id: "abc123def456".to_string(),
            created_at: 1_700_000_000,
            ttl_seconds: 3600,
            nonce: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        }
    }

    #[test]
    fn test_ticket_bs58_roundtrip() {
        let ticket = sample_ticket();
        let encoded = ticket.to_bs58().unwrap();
        let decoded = JoinTicket::from_bs58(&encoded).unwrap();
        assert_eq!(ticket, decoded);
    }

    #[test]
    fn test_ticket_not_expired() {
        let ticket = sample_ticket();
        assert!(!ticket.is_expired(1_700_000_000));
        assert!(!ticket.is_expired(1_700_003_600));
    }

    #[test]
    fn test_ticket_expired() {
        let ticket = sample_ticket();
        assert!(ticket.is_expired(1_700_003_601));
        assert!(ticket.is_expired(1_800_000_000));
    }

    #[test]
    fn test_ticket_decode_invalid_bs58() {
        let result = JoinTicket::from_bs58("not-valid-bs58!!!");
        assert!(result.is_err());
    }

    #[test]
    fn test_ticket_decode_invalid_json() {
        // Valid bs58 but not valid JSON
        let encoded = bs58::encode(b"not json").into_string();
        let result = JoinTicket::from_bs58(&encoded);
        assert!(result.is_err());
    }
}
